language: node_js

node_js:
  - LTS
  - v11
  - v10
  - v8
  - v6
  - v4

cache:
  apt: true
  directories:
    - node_modules

install:
  - npm install -D

script:
  - npm test

after_script: cat ./coverage/lcov.info | coveralls
