language: node_js

node_js:
  - stable
  - v11
  - v10
  - v8
  - v6

cache:
  apt: true
  directories:
    - node_modules

install:
  - npm install -D

script:
  - npm test

after_script: 
  - cat ./coverage/lcov.info | coveralls
  - bash <(curl -s https://codecov.io/bash)
